### ISSUE TITLE
restore chef 11 support?

### ISSUE THREAD

**Issue by joemiller** [hw-cookbooks/route53#89]
It looks like 0.4.2 breaks chef-11 support. It would be nice to keep this support for a little while longer, if it's an easy change (looks like it might be).

```
  ================================================================================
  Recipe Compile Error in /opt/pantheon/infrastructure/cookbooks/onebox/recipes/default.rb
  ================================================================================

  NoMethodError
  -------------
  undefined method `compile_time' for Chef::Resource::ChefGem

  Cookbook Trace:
  ---------------
    /opt/pantheon/infrastructure/cookbooks/route53/recipes/default.rb:24:in `block in from_file'
    /opt/pantheon/infrastructure/cookbooks/route53/recipes/default.rb:22:in `from_file'
    /opt/pantheon/infrastructure/cookbooks/onebox/recipes/route53.rb:5:in `from_file'
    /opt/pantheon/infrastructure/cookbooks/onebox/recipes/base.rb:7:in `from_file'
    /opt/pantheon/infrastructure/cookbooks/onebox/recipes/default.rb:3:in `from_file'

  Relevant File Content:
  ----------------------
  /opt/pantheon/infrastructure/cookbooks/route53/recipes/default.rb:

   17:  # limitations under the License.
   18:  #
   19:
   20:  include_recipe 'xml::ruby'
   21:
   22:  chef_gem "fog" do
   23:    action :install
   24>>   compile_time false
   25:    version node['route53']['fog_version']
   26:  end
   27:
```

**Comment by bshehram** [comment]
+1 on this please! we could really benefit from getting this fixed all of our custom cookbooks in OpsWorks AWS (which uses chef 11) are broken and new instances can't be launched :(

**Comment by slyness** [comment]
Great. Thanks for #90 I'll try and cut a release this weekend.
